### ISSUE TITLE
System.InvalidCastException when using PagingPredicate on Map.EntrySet()

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast-csharp-client#118]
When using a PagingPredicate with Map.EntrySet() (with returning some entries), the following exception is thrown at the client: 

![image](https://user-images.githubusercontent.com/7557235/30699590-0898d3bc-9edd-11e7-97eb-ed0f4eef51c9.png)

```
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection)
   at Hazelcast.Client.Proxy.ClientMapProxy`2.EntrySetWithPagingPredicate(PagingPredicate pagingPredicate)
   at Hazelcast.Client.Proxy.ClientMapProxy`2.EntrySet(IPredicate predicate)
   at ConsoleApplication3.Program.Main(String[] args) in c:\Users\Alparslan\Documents\Visual Studio 2013\Projects\ConsoleApplication3\ConsoleApplication3\Program.cs:line 32
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

The reproducer code is as follows:

```
var map = client.GetMap<int, int>("testMap");
var size = map.EntrySet(new PagingPredicate(3)).Count;
```

Map.KeySet() works smoothly. Client version is 3.8.2.

**Comment by asimarslan** [comment]
Problem is with primitive types. A solution with backward compatibility is needed.
