### ISSUE TITLE
Hazelcast.Net.DependencyInjection NullReference

### ISSUE THREAD

**Issue by rwth-aachen1** [hazelcast/hazelcast-csharp-client#527]
When you add HazelcastOptions to DependencyInjection the class [ServiceCollectionExtensions](https://github.com/hazelcast/hazelcast-csharp-client/blob/master/src/Hazelcast.Net.DependencyInjection/ServiceCollectionExtensions.cs#L56) takes care of that.

# My setup

I'm using an empty ASP.NET Core 3.1 WebApi with `Hazelcast.Net`, `Hazelcast.Net.JetbrainsAnnotations` and `Hazelcast.Net.DependencyInjection` added as project references.

In `Startup.ConfigureServices` I am calling `services.AddHazelcast(Configuration);`.

In `Startup.Configure` I am injecting `HazelcastOptions` and create a new `IHazelcastClient` there. This is just for demonstration purposes.

This is what the methods look like:

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddHazelcast(Configuration);
        }


        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, HazelcastOptions options)
        {

            var client = HazelcastClientFactory.StartNewClientAsync(options).GetAwaiter().GetResult();

            /// more code stuff
        }
```

# The problem

When you resolve `HazelcastOptions` (not `IOptions<HazelcastOptions>`, but the result would most likely be the same if not worse) and pass that object to `HazelcastClientFactory.StartNewClientAsync(options)`, you are getting a NullReferenceException.

Stacktrace:

```
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Hazelcast.Core.SingletonServiceFactory`1.<set_ServiceProvider>b__12_0() in /blah/git/hazelcast-csharp-client/src/Hazelcast.Net/Core/SingletonServiceFactory.cs:line 115
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at System.Lazy`1.get_Value()
         at Hazelcast.Core.SingletonServiceFactory`1.get_Service() in /blah/git/hazelcast-csharp-client/src/Hazelcast.Net/Core/SingletonServiceFactory.cs:line 135
         at Hazelcast.HazelcastClientFactory.CreateClient(HazelcastOptions options) in /blah/git/hazelcast-csharp-client/src/Hazelcast.Net/HazelcastClientFactory.cs:line 217
         at Hazelcast.HazelcastClientFactory.StartNewClientAsyncInternal(HazelcastOptions options, CancellationToken cancellationToken) in /blah/git/hazelcast-csharp-client/src/Hazelcast.Net/HazelcastClientFactory.cs:line 98
```

# The cause

`options.LoggerFactory.ServiceProvider` is `null`.

I am not entirely sure about the cause, but I speculate about `options.ServiceProvider` on [this](https://github.com/hazelcast/hazelcast-csharp-client/blob/37b4f7ae2718396090d4ad613e38155c4ffa7e91/src/Hazelcast.Net.DependencyInjection/ServiceCollectionExtensions.cs#L56) line being not set.

Workaround:

When I'm setting `options.LoggerFactory.ServiceProvider` manually just before passing it to `HazelcastClientFactory.StartNewClientAsync(options)` that NullReferenceException is not thrown and everything works correctly.

# Fix

My proposal would be to move that line into [this](https://github.com/hazelcast/hazelcast-csharp-client/blob/37b4f7ae2718396090d4ad613e38155c4ffa7e91/src/Hazelcast.Net.DependencyInjection/ServiceCollectionExtensions.cs#L48) method, because `IServiceProvider` is available there.

I could provide a pull request if that's wanted.

**Comment by rwth-aachen1** [comment]
This one seems to work, yay!

Thanks for your effort!
