### ISSUE TITLE
ClientPartitionTest.TestPartitionsUpdatedAfterNewNode

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast-csharp-client#60]
```
                         MESSAGE:
                                                Could not verify assertion The partition list did not contain 2 partitions. after 60 seconds: NUnit.Framework.AssertionException:   Expected: 2
  But was:  1

   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Int32 expected, Int32 actual)
   at Hazelcast.Client.Test.HazelcastBaseTest.<AddNodeAndWait>b__2() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\HazelcastBaseTest.cs:line 105
   at Hazelcast.Client.Test.TestSupport.AssertTrueEventually(Action asserAction, Int32 timeoutSeconds, String assertion) in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\TestSupport.cs:line 83
                                                +++++++++++++++++++
                                                STACK TRACE:
                                                at Hazelcast.Client.Test.TestSupport.AssertTrueEventually(Action asserAction, Int32 timeoutSeconds, String assertion) in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\TestSupport.cs:line 92
at Hazelcast.Client.Test.HazelcastBaseTest.AddNodeAndWait() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\HazelcastBaseTest.cs:line 108
at Hazelcast.Client.Test.ClientPartitionTest.TestPartitionsUpdatedAfterNewNode() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\ClientPartitionTest.cs:line 48
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/csharp-client-master/184/testReport/junit/Hazelcast.Client.Test/ClientPartitionTest/TestPartitionsUpdatedAfterNewNode/

**Comment by hasancelik** [comment]
```
MESSAGE:
                                                Could not verify assertion The partition list did not contain 2 partitions. after 60 seconds: NUnit.Framework.AssertionException:   Expected: 2
  But was:  1

   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Int32 expected, Int32 actual)
   at Hazelcast.Client.Test.HazelcastBaseTest.<AddNodeAndWait>b__2() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\HazelcastBaseTest.cs:line 105
   at Hazelcast.Client.Test.TestSupport.AssertTrueEventually(Action asserAction, Int32 timeoutSeconds, String assertion) in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\TestSupport.cs:line 83
                                                +++++++++++++++++++
                                                STACK TRACE:
                                                at Hazelcast.Client.Test.TestSupport.AssertTrueEventually(Action asserAction, Int32 timeoutSeconds, String assertion) in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\TestSupport.cs:line 92
at Hazelcast.Client.Test.HazelcastBaseTest.AddNodeAndWait() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\HazelcastBaseTest.cs:line 108
at Hazelcast.Client.Test.ClientPartitionTest.TestPartitionsUpdatedAfterNewNode() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\ClientPartitionTest.cs:line 48
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/csharp-client-master/185/testReport/Hazelcast.Client.Test/ClientPartitionTest/TestPartitionsUpdatedAfterNewNode/
