### ISSUE TITLE
System.ObjectDisposedException: The semaphore has been disposed [API-1453]

### ISSUE THREAD

**Issue by drieseng** [hazelcast/hazelcast-csharp-client#661]
We regularly hit the following exception in **Hazelcast.Net** version **5.1.0**:
```txt
Hazelcast.Exceptions.ClientOfflineException: Hazelcast client is not connected. ---> Hazelcast.Exceptions.TargetDisconnectedException: Target disconnected. ---> System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at Hazelcast.Core.HSemaphore.Release()
   at Hazelcast.Messaging.ClientMessageConnection.<SendAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hazelcast.Clustering.MemberConnection.<SendAsyncInternal>d__66.MoveNext()
   --- End of inner exception stack trace ---
   at Hazelcast.Clustering.MemberConnection.<SendAsyncInternal>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Hazelcast.Clustering.ClusterMessaging.<SendAsyncInternal>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at Hazelcast.Clustering.ClusterState.ThrowIfNotActive(Exception innerException)
   at Hazelcast.Clustering.ClusterMessaging.<SendAsyncInternal>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hazelcast.Clustering.ClusterMessaging.<SendAsyncInternal>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hazelcast.Clustering.ClusterMessaging.<SendAsyncInternal>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hazelcast.Clustering.ClusterMessaging.<SendToKeyPartitionOwnerAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hazelcast.DistributedObjects.Impl.HMap`2.<GetDataAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hazelcast.DistributedObjects.Impl.HMap`2.<GetAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hazelcast.DistributedObjects.Impl.HMap`2.<GetAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BRail.Nis.Caching.Hazelcast.HazelcastCacheAdapter.<>c__DisplayClass6_0.<<get_Item>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BRail.Nis.Caching.Hazelcast.HazelcastCacheAdapter.get_Item(String key)
   at BRail.Nis.Caching.CacheManager.get_Item(String key)
```

Is this a known issue?
We use a single(ton) instance of the hazelcast client that is shared between multiple threads.
We sometimes have threads that block indefinitely with the following (partial) call stack:

```txt
ntdll!NtWaitForMultipleObjects+14    
KERNELBASE!WaitForMultipleObjectsEx+ef    
clr!WaitForMultipleObjectsEx_SO_TOLERANT+62    
clr!Thread::DoAppropriateWaitWorker+205    
clr!Thread::DoAppropriateWait+7d    
clr!CLREventBase::WaitEx+b6    
clr!Thread::Block+2c    
clr!SyncBlock::Wait+1c8    
clr!ObjectNative::WaitTimeout+e1    
mscorlib_ni!System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)+364    
mscorlib_ni!System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken)+bb    
mscorlib_ni!System.Threading.Tasks.Task.InternalWait(Int32, System.Threading.CancellationToken)+1b1    
mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+d591c3    
BRail.Nis.Caching.Hazelcast.HazelcastCacheAdapter.get_Item(System.String)+96 
```

This is the (sync over async) implementation of **HazelcastCacheAdapter.get_Item(System.String)**:

```cs
public object this[string key]
{
    get { return Task.Run(async () => await _map.GetAsync(key).ConfigureAwait(false)).GetAwaiter().GetResult(); }
}
```

Could this blocking call be related to the **ObjectDisposedException** or other connectivity issues?

**Comment by emreyigit** [comment]
Hey, client must be disposed or shutdown somehow in order to get that exception. If no one disposed it, client may lost its connection and if can't reconnect, will be shutdown eventually. What about the retry strategy and reconnection mode options? Are they set/configure?

**Comment by zpqrtbnk** [comment]
FWIW I am currently looking into this. I feel that there are two different issues here, (a) the `ObjectDisposedException` on the semaphore and (b) the tasks hanging. Of course, sync-over-async does not help :) Out of curiosity, why the `Task.Run` pattern vs this:

```csharp
public object this[string key] => _map.GetAsync(key).GetAwaiter().GetResult();
```

?

**Comment by zpqrtbnk** [comment]
Regarding the first issue, `ObjectDisposeException` on the semaphore, here is what happens:

The connection that is being used for the current call goes down for some reason, while you are trying to use it. This *can* happen (cluster restart? network glitch?) and results in a `TargetDisconnectedException` being throw. Since you are performing a READ operation, what happens next depends on whether *other* connections exist or not.

If other connections were available, the client would transparently try the call again on another connection. Unfortunately, it seems that your client got completely disconnected from the cluster. It is not possible to retry the call. This results in a `ClientOfflineException` which wraps the `TargetDisconnectedException`.

The `ClientOfflineException` bubbles up to your code.

Meanwhile, the client tries its best to reconnect to the cluster. As long as it's not reconnected, all calls will fail with that same `ClientOfflineException`. Once reconnected, operations will resume normally. We do not provide a way to hang calls while the server tries to reconnect (though that is a feature that has been considered and I am happy to discuss it).

Now, what about the `ObjectDisposedException`? When the connection dies, it gets disposed. This includes a semaphore that it owns. Meanwhile, the send operation terminates (with a failure) and wants to release the semaphore. Which has been disposed. There is a check missing in our code, to *not* release the semaphore if it has been released.

-> this we need to fix.

What do you think? Anything I could explain better or we could do better here?

**Comment by zpqrtbnk** [comment]
Regarding the second issue, hanging tasks:

```
ntdll!NtWaitForMultipleObjects+14    
KERNELBASE!WaitForMultipleObjectsEx+ef    
clr!WaitForMultipleObjectsEx_SO_TOLERANT+62    
clr!Thread::DoAppropriateWaitWorker+205    
clr!Thread::DoAppropriateWait+7d    
clr!CLREventBase::WaitEx+b6    
clr!Thread::Block+2c    
clr!SyncBlock::Wait+1c8    
clr!ObjectNative::WaitTimeout+e1    
mscorlib_ni!System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)+364    
mscorlib_ni!System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken)+bb    
mscorlib_ni!System.Threading.Tasks.Task.InternalWait(Int32, System.Threading.CancellationToken)+1b1    
mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+d591c3    
BRail.Nis.Caching.Hazelcast.HazelcastCacheAdapter.get_Item(System.String)+96 
```

This is basically the task that you created in the index property getter, waiting to complete. It's waiting on its own `ManualResetEventSlim` internal instance. But it is hard to tell *what* it is waiting for. At that point... would you have a dump of the process in that state, that would allow us to see the *other* tasks and the global situation?

**Comment by drieseng** [comment]
> This is basically the task that you created in the index property getter, waiting to complete. It's waiting on its own ManualResetEventSlim internal instance. But it is hard to tell what it is waiting for. At that point... would you have a dump of the process in that state, that would allow us to see the other tasks and the global situation?

I indeed have memory dumps of the process in that state. I could share one of these with you, but - to be honest - I feel like I'm already asking too much from you guys (since we're not a paying customer). If you're really willing to investigate this further (thanks!!!), can I upload the file somewhere? If I recall correctly, it's about 1 GB.

**Comment by drieseng** [comment]
> What do you think? Anything I could explain better or we could do better here?

No, you did a great job explaining. Thanks! Is there anything we can do on our end? It's very well possible that we dispose the client from one thread while some async calls are in flight.

The **ObjectDisposedException** itself doesn't bother me all that much, I just want to make sure that this is not causing tasks to block (wait) indefinitely.

**Comment by zpqrtbnk** [comment]
The `ObjectDisposedException` issue will be fixed with [this PR](https://github.com/hazelcast/hazelcast-csharp-client/pull/669) which we still need to assign to a version, etc. I realize how this semaphore-related exception *and* hanging tasks could seem related, but I would tend to think that's not the case.

I'd be happy to look into the dump, just to be sure. If that's OK with you, you can WeTransfer it to me (email would be stephane dot gay at hazelcast dot com).

**Comment by drieseng** [comment]
@zpqrtbnk I'm pretty sure we're dealing with a sync over async deadlock here, but as far as I can tell there's only one `ConfigureAwait(false)` missing in Hazelcast.Net, and that one (#642) does not apply to us (since we're running on .NET Framework 4.8).

**Comment by drieseng** [comment]
@zpqrtbnk I sen your one of our memory dumps via WeTransfer. Let me know if you need more info.
