### ISSUE TITLE
ClientSSLTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast-csharp-client#84]
Hazelcast.Client.Test.ClientSSLTest.TestMapSSLEnabled_DoNotValidateName

```
MESSAGE:
                                                System.InvalidOperationException : Unable to connect to any address in the config! The following addresses were tried:127.0.0.1:5701
                                                +++++++++++++++++++
                                                STACK TRACE:
                                                at Hazelcast.Client.Spi.ClientClusterService.ConnectToOne() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Net\Hazelcast.Client.Spi\ClientClusterService.cs:line 379
at Hazelcast.Client.Spi.ClientClusterService.ConnectToCluster() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Net\Hazelcast.Client.Spi\ClientClusterService.cs:line 333
at Hazelcast.Client.Spi.ClientClusterService.Start() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Net\Hazelcast.Client.Spi\ClientClusterService.cs:line 225
at Hazelcast.Client.HazelcastClient.Start() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Net\Hazelcast.Client\HazelcastClient.cs:line 427
at Hazelcast.Client.HazelcastClient.NewHazelcastClient(ClientConfig config) in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Net\Hazelcast.Client\HazelcastClient.cs:line 329
at Hazelcast.Client.Test.ClientSSLTest.Setup(Boolean ssl, Boolean validateCertificateChain, Boolean validateCertificateName, String certificateName) in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\ClientSSLTest.cs:line 40
at Hazelcast.Client.Test.ClientSSLTest.TestMapSSLEnabled_DoNotValidateName() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\ClientSSLTest.cs:line 74
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/csharp-client-master/267/testReport/Hazelcast.Client.Test/ClientSSLTest/TestMapSSLEnabled_DoNotValidateName/

Hazelcast.Client.Test.ClientSSLTest.TestMapSSLEnabled_validateName_validName

```
MESSAGE:
                                                System.InvalidOperationException : Unable to connect to any address in the config! The following addresses were tried:127.0.0.1:5701
                                                +++++++++++++++++++
                                                STACK TRACE:
                                                at Hazelcast.Client.Spi.ClientClusterService.ConnectToOne() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Net\Hazelcast.Client.Spi\ClientClusterService.cs:line 379
at Hazelcast.Client.Spi.ClientClusterService.ConnectToCluster() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Net\Hazelcast.Client.Spi\ClientClusterService.cs:line 333
at Hazelcast.Client.Spi.ClientClusterService.Start() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Net\Hazelcast.Client.Spi\ClientClusterService.cs:line 225
at Hazelcast.Client.HazelcastClient.Start() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Net\Hazelcast.Client\HazelcastClient.cs:line 427
at Hazelcast.Client.HazelcastClient.NewHazelcastClient(ClientConfig config) in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Net\Hazelcast.Client\HazelcastClient.cs:line 329
at Hazelcast.Client.Test.ClientSSLTest.Setup(Boolean ssl, Boolean validateCertificateChain, Boolean validateCertificateName, String certificateName) in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\ClientSSLTest.cs:line 40
at Hazelcast.Client.Test.ClientSSLTest.TestMapSSLEnabled_validateName_validName() in c:\jenkins\ope-fs-root\workspace\csharp-client-master\Hazelcast.Test\Hazelcast.Client.Test\ClientSSLTest.cs:line 54
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/csharp-client-master/267/testReport/Hazelcast.Client.Test/ClientSSLTest/TestMapSSLEnabled_validateName_validName/

**Comment by asimarslan** [comment]
Master branch is not stable and we do not make releases from master. After the release of 3.7 we will merge maintenance to master to fix these bugs.
