### ISSUE TITLE
ClientTxnMapTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast-csharp-client#86]
**TestKeySetValues**

```
MESSAGE:
                                                  Expected: 3
  But was:  2

                                                +++++++++++++++++++
                                                STACK TRACE:
                                                at Hazelcast.Client.Test.ClientTxnMapTest.TestKeySetValues() in c:\jenkins\ope-fs-root\workspace\csharp-client-maintenance\Hazelcast.Test\Hazelcast.Client.Test\ClientTxnMapTest.cs:line 130
```

**TestPutGet**

```
MESSAGE:
                                                System.InvalidOperationException : Nested transactions are not allowed!
                                                +++++++++++++++++++
                                                STACK TRACE:
                                                at Hazelcast.Util.ExceptionUtil.Rethrow(Exception t) in c:\jenkins\ope-fs-root\workspace\csharp-client-maintenance\Hazelcast.Net\Hazelcast.Util\ExceptionUtil.cs:line 118
at Hazelcast.Client.Request.Transaction.TransactionProxy.Begin() in c:\jenkins\ope-fs-root\workspace\csharp-client-maintenance\Hazelcast.Net\Hazelcast.Client.Request.Transaction\TransactionProxy.cs:line 72
at Hazelcast.Client.Request.Transaction.TransactionContextProxy.BeginTransaction() in c:\jenkins\ope-fs-root\workspace\csharp-client-maintenance\Hazelcast.Net\Hazelcast.Client.Request.Transaction\TransactionContextProxy.cs:line 43
at Hazelcast.Client.Test.ClientTxnMapTest.TestPutGet() in c:\jenkins\ope-fs-root\workspace\csharp-client-maintenance\Hazelcast.Test\Hazelcast.Client.Test\ClientTxnMapTest.cs:line 40
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/csharp-client-maintenance/560/

**Comment by asimarslan** [comment]
Not failing anymore
